### PR TITLE
Add New Example

### PR DESCRIPTION
**Pull request by ncteisen**
To answer the question: "I wonder if there was ever an elite eight in which all one seeds were eliminated?"

### CODE REVIEW

**Comment by danvk** [comment]
Love it! What's the answer?

(Also curious how you find this repo)

**Comment by danvk** [comment]
Looks like the answer is "no." Merging, thanks for the contribution. Keep 'em coming!

```
$ python one_seeds_eliminated.py pages/*.json
In 1989, no one seeds remained in the round of 2
In 1991, no one seeds remained in the round of 2
In 1998, no one seeds remained in the round of 2
In 2003, no one seeds remained in the round of 2
In 2004, no one seeds remained in the round of 2
In 2006, no one seeds remained in the round of 4
In 2011, no one seeds remained in the round of 4
In 2014, no one seeds remained in the round of 2
```

**Comment by ncteisen** [comment]
I was looking to do the same thing, and googled 'march madness data json', and this repo came up!

**Comment by danvk** [comment]
The miracle of open source & Google -- I did the same search two weeks ago,
got no results and spent an afternoon making this :)

**Pull request merged**
